# SPDX-FileCopyrightText: 2023 Norbert Melzer <timmelzer@gmail.com>
#
# SPDX-License-Identifier: MIT

[workspace]
resolver = "2"

members = [
  "time_rs",
]

[workspace.package]
authors = [
    "Norbert Melzer <nmelzer@nobbz.dev>",
]
license = "MIT"
version = "0.1.0"
